
export const data = [
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
    {
        id: 1,
        AttendanceLogNo: "134494",
        EmployeeName : "Jane Doe",
        CheckInDate: "10 Jun 2022",
        CheckInTime:"09:04",
        CheckOutDate:"10 Jun 2022",
        CheckOutTime:"18:04",
        WorkHours:"8.00",
        ExtraWorkingHours:"8",
        Validity:"invalid",
    },
]